version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-https
    ports:
      - "9023:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - .:/usr/share/nginx/html:ro  # Ajoute ça : monte ton dossier local comme racine web
    restart: unless-stopped
